MODEL:
  TYPE: iddwnet
  NAME: iddwnet_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  DWNET:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    WINDOW_SIZE: 7
    DYNAMIC: True
    INHOMO: True
    INHOMO_HEADS: [ 4, 8, 16, 32 ]
AMP_OPT_LEVEL: "O0"
